# -*- coding: utf-8 -*-
"""Example preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nubzPLMjTkcGyBgUT4X8ze8RQq9AezlF
"""

import pandas as pd
import os


# define file paths
DATA_DIR = "data"
OUTPUT_FILE = os.path.join(DATA_DIR, "merged_data.csv")

def load_data(): #load raw CSV files into DataFrame
# return caloric_supply, gdp_per_capita, healthcare_expenditure, life_expectancy

def filter_us_data(df): #filter for US data only
    return df[df["Entity"] == "United States"]

def preprocess_data(): # preprocess data by filtering, cleaning, merging, and saving to CSV
    # load data
    caloric_supply, gdp_per_capita, healthcare_expenditure, life_expectancy = load_data()

    # merge the dataframes on 'Year'

# rename column names
    merged_df.rename(columns={"Daily calorie supply per person": "Daily calorie supply",
                            "GDP per capita, PPP (constant 2021 international $)":"GDP per capita",
                            "Current health expenditure (CHE) as percentage of gross domestic product (GDP) (%)":"Health expenditure as percentage of GDP",
                            "Period life expectancy at birth - Sex: total - Age: 0":"Life expectancy"},
                            inplace=True)

    # save the processed dataset to a CSV file in the data folder

    def main():
      preprocess_data()

    if __name__ == "__main__":
      main()